// Generated by scripts/prepare-world-life.mjs from the official assets.
export const ASSET_DATA = {
  maple: {
    width: 32,
    height: 46,
    biomes: [2, 6],
    mirror: false,
  },
  sapling: {
    width: 20,
    height: 33,
    biomes: [2, 6],
    mirror: false,
  },
  seedling: {
    width: 9,
    height: 12,
    biomes: [2, 6],
    mirror: false,
  },
  stump: {
    width: 14,
    height: 12,
    biomes: [1, 2, 3, 6],
    mirror: false,
  },
  forest: {
    width: 40,
    height: 52,
    biomes: [2, 6],
    mirror: false,
  },
  jungle: {
    width: 38,
    height: 54,
    biomes: [1],
    mirror: false,
  },
  acacia: {
    width: 52,
    height: 51,
    biomes: [4],
    mirror: false,
  },
  palm: {
    width: 41,
    height: 54,
    biomes: [1, 5],
    mirror: false,
  },
  snowPine: {
    width: 35,
    height: 52,
    biomes: [3, 8],
    mirror: false,
  },
  pine: {
    width: 35,
    height: 52,
    biomes: [3, 8],
    mirror: false,
  },
  grass: {
    width: 16,
    height: 16,
    biomes: [1, 2, 4, 6],
    mirror: false,
  },
} as const;
