/** Original discrete pixel motifs. Spaces are transparent; l/m/d use palette swapping. */
export const CLUSTERS = {
  GrassCluster: [" l   l ", " lm lm ", "  mdm  ", "   d   "],
  DirtCluster: ["  mm   ", " mmlmm ", "mmlmmd ", " mddd  "],
  RockCluster: ["  ll  ", " lmmm ", " mmmdd", "  ddd "],
  SandCluster: ["     lll   ", "   llmmml  ", " llmmmddd  ", "     ddd   "],
  SnowCluster: ["  llll  ", " lllllm ", "  mmmd  ", "   dd   "],
  WaterCluster: ["    mmmm   ", " mmmmmmmm  ", "   ddddd   "],
  WaveCluster: ["    llll    ", " lllmmm     ", "      mm    "],
  MountainCluster: [
    "        l        ",
    "       llm       ",
    "      lllmd      ",
    "     lllmmdd     ",
    "    lllmmmddd    ",
    "   lllmlmmdddd   ",
    "  llmmmlmmmdddd  ",
    " lmmmdmmmmmddddd ",
    "  mmmdddmmdddddd ",
    "    dddddddddd   ",
  ],
  ShallowWaterCluster: ["  lll    ", " lmmllll ", "  mmm    "],
  BeachCluster: ["  llmmm  ", " llmmm   ", "  mmd    "],
  DryGrassCluster: [" l  l  ", " lm l l", "  mmdm ", "   dd  "],
  LeafCluster: [" ll   m ", " lmm mm ", "  d  d  "],
  IceCrackCluster: [
    " l       ",
    " ml      ",
    "  ml     ",
    "   mll   ",
    "     ml  ",
    "      ml ",
  ],
  RootCluster: [" m      ", " mm  m  ", "  mdm   ", "  m dd  ", " m   d  "],
  CanopyCluster: [
    "   ll   ",
    " lllmmm ",
    "llmmmmd ",
    " mmmddd ",
    "  mddd  ",
    "   md   ",
    "   dd   ",
  ],
} as const;
export type ClusterKind = keyof typeof CLUSTERS;
export const GROUND_PALETTES = [
  ["#123e69", "#185682", "#206b96", "#3389ad", "#56b7c1"],
  ["#245d3d", "#307849", "#408950", "#579a57", "#76b361"],
  ["#42783d", "#548f42", "#6aa149", "#81b658", "#9ac972"],
  ["#294e45", "#386653", "#487b60", "#608e70", "#84a088"],
  ["#8e963f", "#a5aa4c", "#b8b358", "#ccc16b", "#ddd385"],
  ["#b38246", "#c79750", "#d9ad61", "#e8c37b", "#f4d996"],
  ["#648b43", "#7d9d4a", "#92b158", "#a9c270", "#bfd28c"],
  ["#6c807a", "#869389", "#a1ab9c", "#b8c0ad", "#d6dfcf"],
  ["#4b5862", "#687077", "#8b8d89", "#afb2a8", "#dbe1d8"],
  ["#83b8cb", "#a3d1df", "#c4e4e8", "#e1f2ed", "#f5faf0"],
] as const;
