export const natureLabel: Record<string, string> = {
  oak: "Carvalho",
  youngOak: "Carvalho jovem",
  birch: "Bétula",
  conifer: "Conífera",
  snowConifer: "Conífera nevada",
  tropical: "Árvore tropical",
  savanna: "Acácia",
  coconut: "Palmeira",
  stone: "Pedra",
  sandstone: "Arenito",
  iron: "Ferro",
  copper: "Cobre",
  coal: "Carvão",
  crystal: "Cristal",
  Wood: "Madeira",
  Stone: "Pedra",
  Iron: "Ferro",
  Copper: "Cobre",
  Coal: "Carvão",
  Crystal: "Cristal",
  Food: "Alimento",
  Metal: "Metal",
  Energy: "Energia",
  SEEDLING: "Muda",
  YOUNG: "Jovem",
  MATURE: "Adulta",
  OLD: "Antiga",
  DAMAGED: "Sendo cortada",
  FALLING: "Caindo",
  FALLEN: "Toco",
  DECOMPOSING: "Decomposição",
  RESPAWNING: "Regeneração",
  AVAILABLE: "Disponível",
  EXHAUSTED: "Esgotado",
  CLEAR: "Céu limpo",
  CLOUDY: "Nublado",
  LIGHT_RAIN: "Chuva leve",
  RAIN: "Chuva",
  WINDY: "Vento",
  Walking: "Caminhando",
  Exploring: "Explorando",
  Working: "Trabalhando",
  Mining: "Minerando",
  Gathering: "Cortando",
  Transporting: "Transportando",
  Storing: "Armazenando",
  Building: "Construindo",
  Farming: "Cultivando",
  Eating: "Comendo",
  Resting: "Descansando",
};
export const labelNature = (value: string) => natureLabel[value] ?? value;
